sudo: false

language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"
  - "8"
  - "iojs"

before_script:
  - npm install -g grunt-cli

matrix:
  fast_finish: true

cache:
  directories:
    - node_modules
